#!/bin/sh

# webhook URL: this URL is hit with a POST request when you push
url="http://www.postbin.org/w6zemu"


read oldrev newrev refname

refname=${refname##refs/heads/}

gitver=$(git --version)
gitver=${gitver##* }

rev=$(git describe ${newrev} 2>/dev/null)
[[ -z ${rev} ]] && rev=${newrev:0:12}

rawcommit=$(git cat-file commit ${newrev})

author=$(sed -n -e '/^author \([^<]*\).*$/s--\1-p' \
	<<< "${rawcommit}")
author=$(echo ${author} | sed -e 's/[ ]*$//')

email=$(sed -n -e '/^author .*<\([^>]*\).*$/s--\1-p' \
	<<< "${rawcommit}")

logmessage=$(sed -e '1,/^$/d' <<< "${rawcommit}")
logmessage=${logmessage//&/&amp;}
logmessage=${logmessage//</&lt;}
logmessage=${logmessage//>/&gt;}

ts=$(sed -n -e '/^author .*> \([0-9]\+\).*$/s--\1-p' \
	<<< "${rawcommit}")

out="
{
  \"after\": \"${newrev}\", 
  \"before\": \"${oldrev}\", 
  \"commits\": [
    {
      \"added\": [
$(git diff-tree -r --name-only --diff-filter=A ${newrev} | sed -e '1d' -e 's-.*-        \"&\",-' | sed -e '$s/,//')
      ], 
      \"author\": {
        \"email\": \"${email}\", 
        \"name\": \"${author}\"
      }, 
      \"id\": \"${rev}\", 
      \"message\": \"${logmessage}\", 
      \"modified\": [
$(git diff-tree -r --name-only --diff-filter=M ${newrev} | sed -e '1d' -e 's-.*-        \"&\",-' | sed -e '$s/,//')
      ], 
      \"removed\": [
$(git diff-tree -r --name-only --diff-filter=D ${newrev} | sed -e '1d' -e 's-.*-        \"&\",-' | sed -e '$s/,//')
      ], 
      \"timestamp\": \"${ts}\"
    }
  ], 
  \"ref\": \"${refname}\"
}"

wget --post-data "payload=${out}" ${url} --quiet -o /dev/null
